const data = {
  products: [
    {
      id: "1",
      name: "Nike shirt",
      category: "Shirts",
      price: 120,
      countInStock: 28,
      brand: "Nike",
      image: "/img/p1.jpg",
      rating: 4.5,
      numReview: 10,
      description: "high quality product",
    },
    {
      id: "2",
      name: "Addidas shorts",
      category: "Shorts",
      price: 100,
      countInStock: 0,
      brand: "Addidas",
      image: "/img/p2.jpg",
      rating: 4.0,
      numReview: 14,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Lacoste shirt",
      category: "Shirts",
      price: 150,
      countInStock: 15,
      brand: "Lacoste",
      image: "/img/p3.jpg",
      rating: 4.5,
      numReview: 11,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Puma pants",
      category: "Panst",
      price: 70,
      countInStock: 100,
      brand: "Puma",
      image: "/img/p4.jpg",
      rating: 3,
      numReview: 7,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Nike pants",
      category: "Pants",
      price: 120,
      countInStock: 52,
      brand: "Nike",
      image: "/img/p5.jpg",
      rating: 5,
      numReview: 15,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Champion shirt",
      category: "Shirts",
      price: 80,
      countInStock: 44,
      brand: "Champion",
      image: "/img/p6.jpeg",
      rating: 3.5,
      numReview: 9,
      description: "high quality product",
    },
  ],
};

export default data;
